training_setting:
  device: auto
  load_pretrain_model: false
  pretrain_model_path: ./run/train/pretrain_model_folder/
  save_path: ./run/train/
  episodes: 5000
  max_steps: 700
  save_episodes:
    - 1000
    - 2000
    - 3000
    - 4000
  Env:
    env_class: AirsimEnv
    resize: 
      width: 128
      height: 128

  Algorithm: DDPG

testing_setting:
  model_path: ./run/train/test_model_folder/
  test_episodes: 100
  save_path: ./run/test/